osixia/phpldapadmin
osixia/openldap
irasnyd/freeradius-ldap
#docker-compose.yml
version: '3.7'
services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=core
      - LDAP_DOMAIN=core.wsr
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=core,dc=wsr"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=core.wsr.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap
  radius:
    image: irasnyd/freeradius-ldap
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      - "LDAP_HOST=openldap"
      - "LDAP_USER=cn=admin,dc=core,dc=wsr"
      - "LDAP_PASS=admin_pass"
      - "LDAP_BASEDN=dc=core,dc=wsr"
      - "LDAP_USER_BASEDN=ou=ldap,dc=core,dc=wsr"
      - "LDAP_GROUP_BASEDN=ou=ldap,dc=core,dc=wsr"
      - "RADIUS_CLIENT_CREDENTIALS=*:testing123"
    depends_on:
      - openldap
    networks:
      - openldap
networks:
  openldap:
    driver: bridge
